### ISSUE TITLE
Initial setup not working

### ISSUE THREAD

**Issue by rickwargo** [kata-seeds/js-seed#4]
On my MacBookPro, after clone the repository and typing make, I get the following:

```
RickPro:Kata rick$ git clone https://github.com/kata-seeds/js-karma-seed.git
Cloning into 'js-karma-seed'...
remote: Counting objects: 55, done.
remote: Total 55 (delta 0), reused 0 (delta 0), pack-reused 55
Unpacking objects: 100% (55/55), done.
Checking connectivity... done.
RickPro:Kata rick$ cd js-karma-seed/
RickPro:js-karma-seed rick$ make
which node npm phantomjs
/usr/local/bin/node
/usr/local/bin/npm
make: *** [dependencies] Error 1
```

I need to execute `npm install phantomjs` followed by `npm install` to get the environment to function correctly.
Not sure why make is not making.

**Comment by justincampbell** [comment]
@rickwargo Try `brew install phantomjs`. The Makefile could be a lot smarter for installing required packages on different operating systems.

**Comment by rickwargo** [comment]
Thanks @justincampbell. I was able to install with npm - the issue, as you are aware, was with the Makefile to make it easier to set up. Jearvon asked me to open a ticket about it.

**Comment by pselle** [comment]
@justincampbell added the phantomjs to the makefile when it's a node package and not necessarily in the global namespace. Added phantom to the package.json so it's installed correctly, and now a fresh clone works for me. Verification welcome.

**Comment by justincampbell** [comment]
@pselle Thanks!

This seems like it should work now.
